package edu.ve.unimet.supermetromendeley;

import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * 
 * 
 *
 * @author biancazullo
 * @author remo
 * @since Nov 12, 2025
 */
public class Main extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(Main.class.getName());
    private final DefaultListModel<String> articleListModel = new DefaultListModel<>();
    private final ArticleManager articleManager = new ArticleManager();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents(); // <-- deja tu versión generada por NetBeans

        // Enlazar el modelo a la JList
        articleList.setModel(articleListModel);

        // Listener de selección de artículo
        articleList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    String selectedTitle = articleList.getSelectedValue();
                    if (selectedTitle == null) {
                        return;
                    }

                    Article art = articleManager.getArticle(selectedTitle);
                    if (art == null) {
                        return;
                    }

                    // Título
                    articleTitle.setText(art.title);
                    articleTitle.setEnabled(true);

                    // Cuerpo
                    articleBody.setText(art.body);
                    articleBody.setEnabled(true);

                    // Autores
                    String authors = "Autores: ";
                    List<String>.Node<String> authorNode = art.authors.getFirstNode();

                    while (authorNode != null) {
                        authors += authorNode.value + ", ";
                        authorNode = authorNode.next;
                    }

                    if (authors.length() > "Autores: ".length()) {
                        authors = authors.substring(0, authors.length() - 2);
                    }

                    articleAuthors.setText(authors);
                    articleAuthors.setEnabled(true);

                    // Palabras clave + frecuencias (usamos ArticleManager)
                    String keywordsText = articleManager.buildKeywordSummary(art);
                    articleKeywords.setText(keywordsText);
                    articleKeywords.setEnabled(true);
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        articleList = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        addArticleButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        articleBody = new javax.swing.JTextArea();
        articleKeywords = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        articleTitle = new javax.swing.JTextArea();
        articleAuthors = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        articleList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(articleList);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        addArticleButton.setText("Añadir resumen");
        addArticleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addArticleButtonActionPerformed(evt);
            }
        });

        articleBody.setEditable(false);
        articleBody.setColumns(20);
        articleBody.setLineWrap(true);
        articleBody.setRows(5);
        articleBody.setWrapStyleWord(true);
        articleBody.setEnabled(false);
        jScrollPane2.setViewportView(articleBody);

        articleKeywords.setText("Palabras clave:");
        articleKeywords.setEnabled(false);

        articleTitle.setEditable(false);
        articleTitle.setColumns(20);
        articleTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        articleTitle.setLineWrap(true);
        articleTitle.setRows(1);
        articleTitle.setText("Titulo");
        articleTitle.setWrapStyleWord(true);
        articleTitle.setBorder(null);
        articleTitle.setEnabled(false);
        articleTitle.setFocusable(false);
        articleTitle.setOpaque(false);
        jScrollPane3.setViewportView(articleTitle);

        articleAuthors.setText("Autores:");
        articleAuthors.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addArticleButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(articleKeywords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(articleAuthors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(articleAuthors)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(articleKeywords, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addArticleButton)
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addArticleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addArticleButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de texto", "txt");
        chooser.setFileFilter(filter);
        chooser.setMultiSelectionEnabled(false);

        int retVal = chooser.showOpenDialog(this);

        if (retVal == JFileChooser.APPROVE_OPTION) {
            try {
                // Le delegamos toda la lógica a ArticleManager
                Article art = articleManager.addArticleFromFile(chooser.getSelectedFile());

                if (art == null) {
                    // Puede ser archivo vacío o título duplicado
                    JOptionPane.showMessageDialog(this,
                            "El archivo está vacío o el artículo ya fue cargado.");
                    return;
                }

                // Añadir título al modelo de la lista
                articleListModel.addElement(art.title);

                // Ordenar títulos alfabéticamente
                String[] titles = new String[articleListModel.size()];
                for (int i = 0; i < articleListModel.size(); i++) {
                    titles[i] = articleListModel.get(i);
                }

                Arrays.sort(titles);

                articleListModel.clear();
                for (String title : titles) {
                    articleListModel.addElement(title);
                }

            } catch (FileNotFoundException e) {
                JOptionPane.showMessageDialog(this, "No se pudo cargar el archivo solicitado.");
            }
        }
    }//GEN-LAST:event_addArticleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addArticleButton;
    private javax.swing.JLabel articleAuthors;
    private javax.swing.JTextArea articleBody;
    private javax.swing.JLabel articleKeywords;
    private javax.swing.JList<String> articleList;
    private javax.swing.JTextArea articleTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
