package edu.ve.unimet.supermetromendeley;

import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Interfaz principal del sistema. Permite cargar, buscar y visualizar
 * investigaciones, así como consultar autores y palabras clave.
 *
 * @author biancazullo
 * @author remo
 * @since Nov 12, 2025
 */
public class Main extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(Main.class.getName());
    private final DefaultListModel<String> articleListModel = new DefaultListModel<>();
    private final ArticleManager articleManager = new ArticleManager();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        articleList.setModel(articleListModel);
        
        List<String> titles = articleManager.getAllTitles();
        List<String>.Node<String> node = titles.getFirstNode();

        while (node != null) {
            articleListModel.addElement(node.value);
            node = node.next;
        }

        articleList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    String selectedTitle = articleList.getSelectedValue();
                    if (selectedTitle == null) {
                        return;
                    }

                    Article art = articleManager.getArticle(selectedTitle);
                    if (art == null) {
                        return;
                    }

                    articleTitle.setText(art.title);
                    articleTitle.setEnabled(true);

                    articleBody.setText(art.body);
                    articleBody.setEnabled(true);

                    String authors = "Autores: ";
                    List<String>.Node<String> authorNode = art.authors.getFirstNode();

                    while (authorNode != null) {
                        authors += authorNode.value + ", ";
                        authorNode = authorNode.next;
                    }

                    if (authors.length() > "Autores: ".length()) {
                        authors = authors.substring(0, authors.length() - 2);
                    }

                    articleAuthors.setText(authors);
                    articleAuthors.setEnabled(true);

                    String keywordsText = articleManager.buildKeywordSummary(art);
                    articleKeywords.setText(keywordsText);
                    articleKeywords.setEnabled(true);
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        articleList = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        addArticleButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        articleBody = new javax.swing.JTextArea();
        articleKeywords = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        articleTitle = new javax.swing.JTextArea();
        articleAuthors = new javax.swing.JLabel();
        searchByKeywordButton = new javax.swing.JButton();
        searchByAuthorButton = new javax.swing.JButton();
        listKeywordsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        articleList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(articleList);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        addArticleButton.setText("Añadir resumen");
        addArticleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addArticleButtonActionPerformed(evt);
            }
        });

        articleBody.setEditable(false);
        articleBody.setColumns(20);
        articleBody.setLineWrap(true);
        articleBody.setRows(5);
        articleBody.setWrapStyleWord(true);
        articleBody.setEnabled(false);
        jScrollPane2.setViewportView(articleBody);

        articleKeywords.setText("Palabras clave:");
        articleKeywords.setEnabled(false);

        articleTitle.setEditable(false);
        articleTitle.setColumns(20);
        articleTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        articleTitle.setLineWrap(true);
        articleTitle.setRows(1);
        articleTitle.setText("Titulo");
        articleTitle.setWrapStyleWord(true);
        articleTitle.setBorder(null);
        articleTitle.setEnabled(false);
        articleTitle.setFocusable(false);
        articleTitle.setOpaque(false);
        jScrollPane3.setViewportView(articleTitle);

        articleAuthors.setText("Autores:");
        articleAuthors.setEnabled(false);

        searchByKeywordButton.setText("Buscar por palabra clave");
        searchByKeywordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByKeywordButtonActionPerformed(evt);
            }
        });

        searchByAuthorButton.setText("Buscar por autor");
        searchByAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByAuthorButtonActionPerformed(evt);
            }
        });

        listKeywordsButton.setText("Listar palabras claves");
        listKeywordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listKeywordsButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Salir");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(addArticleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchByAuthorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchByKeywordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listKeywordsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(exitButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(articleKeywords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(articleAuthors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(articleAuthors)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(articleKeywords, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addArticleButton)
                                    .addComponent(searchByKeywordButton)
                                    .addComponent(exitButton))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(searchByAuthorButton)
                                    .addComponent(listKeywordsButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addArticleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addArticleButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de texto", "txt");
        chooser.setFileFilter(filter);
        chooser.setMultiSelectionEnabled(false);

        int retVal = chooser.showOpenDialog(this);

        if (retVal == JFileChooser.APPROVE_OPTION) {
            try {
                Article art = articleManager.addArticleFromFile(chooser.getSelectedFile());

                if (art == null) {
                    JOptionPane.showMessageDialog(this,
                            "El archivo está vacío o el artículo ya fue cargado.");
                    return;
                }

                articleListModel.addElement(art.title);

                String[] titles = new String[articleListModel.size()];
                for (int i = 0; i < articleListModel.size(); i++) {
                    titles[i] = articleListModel.get(i);
                }

                Arrays.sort(titles);

                articleListModel.clear();
                for (String title : titles) {
                    articleListModel.addElement(title);
                }

            } catch (FileNotFoundException e) {
                JOptionPane.showMessageDialog(this, "No se pudo cargar el archivo solicitado.");
            }
        }
    }//GEN-LAST:event_addArticleButtonActionPerformed

    private void searchByKeywordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByKeywordButtonActionPerformed
        List<String> keywordsList = articleManager.listAllKeywordsInOrder();
        List<String>.Node<String> node = keywordsList.getFirstNode();

        if (node == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay palabras clave registradas todavía.",
                    "Buscar por palabra clave",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        int count = 0;
        List<String>.Node<String> tmp = node;
        while (tmp != null) {
            count++;
            tmp = tmp.next;
        }

        String[] keywordOptions = new String[count];
        int i = 0;
        while (node != null) {
            keywordOptions[i++] = node.value;
            node = node.next;
        }

        String selectedKeyword = (String) JOptionPane.showInputDialog(
                this,
                "Selecciona una palabra clave:",
                "Buscar por palabra clave",
                JOptionPane.QUESTION_MESSAGE,
                null,
                keywordOptions,
                keywordOptions[0]
        );

        if (selectedKeyword == null) {
            return;
        }

        List<Article> articlesWithKeyword = articleManager.searchByKeyword(selectedKeyword);
        List<Article>.Node<Article> artNode = articlesWithKeyword.getFirstNode();

        if (artNode == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay investigaciones asociadas a la palabra clave seleccionada.",
                    "Sin resultados",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        int artCount = 0;
        List<Article>.Node<Article> tmpArt = artNode;
        while (tmpArt != null) {
            artCount++;
            tmpArt = tmpArt.next;
        }

        String[] articleOptions = new String[artCount];
        int j = 0;
        while (artNode != null) {
            articleOptions[j++] = artNode.value.title;
            artNode = artNode.next;
        }

        String selectedTitle = (String) JOptionPane.showInputDialog(
                this,
                "Selecciona una investigación:",
                "Resultados para \"" + selectedKeyword + "\"",
                JOptionPane.QUESTION_MESSAGE,
                null,
                articleOptions,
                articleOptions[0]
        );

        if (selectedTitle == null) {
            return;
        }

        articleList.setSelectedValue(selectedTitle, true);
    }//GEN-LAST:event_searchByKeywordButtonActionPerformed

    private void searchByAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByAuthorButtonActionPerformed
        List<String> authorsList = articleManager.listAllAuthorsInOrder();
        List<String>.Node<String> node = authorsList.getFirstNode();

        if (node == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay autores registrados todavía.",
                    "Buscar por autor",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        int count = 0;
        List<String>.Node<String> tmp = node;
        while (tmp != null) {
            count++;
            tmp = tmp.next;
        }

        String[] authorOptions = new String[count];
        int i = 0;
        while (node != null) {
            authorOptions[i++] = node.value;
            node = node.next;
        }

        String selectedAuthor = (String) JOptionPane.showInputDialog(
                this,
                "Selecciona un autor:",
                "Buscar por autor",
                JOptionPane.QUESTION_MESSAGE,
                null,
                authorOptions,
                authorOptions[0]
        );

        if (selectedAuthor == null) {
            return;
        }

        List<Article> articlesByAuthor = articleManager.searchByAuthor(selectedAuthor);
        List<Article>.Node<Article> artNode = articlesByAuthor.getFirstNode();

        if (artNode == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay investigaciones asociadas al autor seleccionado.",
                    "Sin resultados",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        int artCount = 0;
        List<Article>.Node<Article> tmpArt = artNode;
        while (tmpArt != null) {
            artCount++;
            tmpArt = tmpArt.next;
        }

        String[] articleOptions = new String[artCount];
        int j = 0;
        while (artNode != null) {
            articleOptions[j++] = artNode.value.title;
            artNode = artNode.next;
        }

        String selectedTitle = (String) JOptionPane.showInputDialog(
                this,
                "Selecciona una investigación:",
                "Resultados para \"" + selectedAuthor + "\"",
                JOptionPane.QUESTION_MESSAGE,
                null,
                articleOptions,
                articleOptions[0]
        );

        if (selectedTitle == null) {
            return;
        }

        articleList.setSelectedValue(selectedTitle, true);
    }//GEN-LAST:event_searchByAuthorButtonActionPerformed

    private void listKeywordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listKeywordsButtonActionPerformed
        List<String> keywordsList = articleManager.listAllKeywordsInOrder();
        List<String>.Node<String> node = keywordsList.getFirstNode();

        if (node == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay palabras claves registradas todavía.",
                    "Listar palabras claves",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.append("Palabras claves registradas (orden alfabético):\n\n");

        while (node != null) {
            sb.append("- ").append(node.value).append("\n");
            node = node.next;
        }

        JOptionPane.showMessageDialog(
                this,
                sb.toString(),
                "Listado de palabras claves",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_listKeywordsButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Main m = new Main();
            m.setLocationRelativeTo(null);
            m.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addArticleButton;
    private javax.swing.JLabel articleAuthors;
    private javax.swing.JTextArea articleBody;
    private javax.swing.JLabel articleKeywords;
    private javax.swing.JList<String> articleList;
    private javax.swing.JTextArea articleTitle;
    private javax.swing.JButton exitButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton listKeywordsButton;
    private javax.swing.JButton searchByAuthorButton;
    private javax.swing.JButton searchByKeywordButton;
    // End of variables declaration//GEN-END:variables
}
